### ISSUE TITLE
Error fetching data and Fetch Rest

### ISSUE THREAD

**Issue by tamet83** [mad-ady/home-assistant-customizations#2]
Hi,

i tried to use your custom_component because I have a similar situation as yours with tautulli monitor sensor. What i need is to extract the attribute values for each user. The structure is this one:

`Top Movie: null
Top TV Show: null
Top User: null
stream_count: 1
total_bandwidth: 5834
stream_count_transcode: 0
wan_bandwidth: 0
stream_count_direct_play: 0
lan_bandwidth: 5834
stream_count_direct_stream: 1
tamet: {
  "Activity": "playing",
  "title": "Venom",
  "transcode_decision": "copy",
  "bandwidth": "5834"
}
Corrado: {
  "Activity": null,
  "title": "",
  "transcode_decision": "",
  "bandwidth": ""
}
Samsung TV: {
  "Activity": null,
  "title": "",
  "transcode_decision": "",
  "bandwidth": ""
}
friendly_name: Tautulli
icon: mdi:plex`

what i'd like to extrat, for each user, are the following attributes:
Ativity
Title
transcode_decision
bandwith

but i don't know why i receive the following erros:
`ERROR (SyncWorker_3) [custom_components.sensor.jsonrest] Error fetching data: <PreparedRequest [GET]>`

and

`ERROR (SyncWorker_3) [custom_components.sensor.jsonrest] Unable to fetch REST data`

Could you please help me?
Thanks in advance

**Comment by mad-ady** [comment]
The errors signify that the module couldn't get the data. Can you try with
curl or wget to test your URL and see if it replies with a json header (and
the data you want)?

By the way, the module should no longer be needed. The current official
rest component can extract some parameters if you specify them:
  - platform: rest
    resource: !secret samygo_tv_living_channelinfo
    method: GET
    name: TV Living ChannelInfo
    json_attributes:
      - source
      - pvr_status
      - power_state
      - tv_mode
      - volume
      - channel_number
      - channel_name
      - program_name
    scan_interval: '00:05'

**Comment by tamet83** [comment]
Hi because the url is on https i had to type the following command on curl:

` curl --insecure -X GET https://my.internal.ip:8123/api/states/sensor.t                                                                                                                                                             autulli?api_password=My_Api_Password`

The response is as follow:

`{"attributes": {"Corrado": {"Activity": null, "bandwidth": "", "title": "", "tra                                                                                                                                                             nscode_decision": ""}, "Samsung TV": {"Activity": null, "bandwidth": "", "title"                                                                                                                                                             : "", "transcode_decision": ""}, "Top Movie": null, "Top TV Show": null, "Top Us                                                                                                                                                             er": null, "friendly_name": "Tautulli", "icon": "mdi:plex", "lan_bandwidth": 0,                                                                                                                                                              "stream_count": "0", "stream_count_direct_play": 0, "stream_count_direct_stream"                                                                                                                                                             : 0, "stream_count_transcode": 0, "tamet": {"Activity": null, "bandwidth": "", "                                                                                                                                                             title": "", "transcode_decision": ""}, "total_bandwidth": 0, "wan_bandwidth": 0}                                                                                                                                                             , "context": {"id": "71bf53b46f6447bbb320d61ddbd36940", "user_id": null}, "entit                                                                                                                                                             y_id": "sensor.tautulli", "last_changed": "2019-02-03T13:17:44.296877+00:00", "l `

I don't understand why the rest platform doesn't work. Does it depend on the fact that i'm using an HTTPS url?

Just to give you more information, the code is the following:

- platform: rest
  resource: !secret tautulli_sensor
  method: GET
  name: Plex Tamet
  verify_ssl: false
  json_attributes:
    - tamet
  scan_interval: '00:05'

**Comment by mad-ady** [comment]
There's a verify_ssl option in the rest sensor you can set to false.
https://www.home-assistant.io/components/sensor.rest/

**Comment by mad-ady** [comment]
Closed for inactivity
